services:
  app:
    container_name: fastAPI_rfc
    image: fastapi-rfc:1.1
    ports:
      - "8083:8080"
    volumes:
      - ./app:/app/app
    networks:
      - rfc_network
    env_file:
      - .env

networks:
  rfc_network:
    driver: bridge
    name: rfc_network




